I am updating this line...26th jan-Republic Day....
This is the master branch code....
This line updating in dev branch
=======
This line updating in dev branch...
>>>>>>> developement
Hello this file contains database related code...
having some utilities for connection
